/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package org.eclipse.lyo.validate;

/**
 * 
 * @author Yash Khatri (yash.s.khatri@gmail.com)
 *
 */

public interface SampleAdaptorConstants
{
    public static String SAMPLEDOMAIN_DOMAIN = "http://www.sampledomain.org/sam#";
    public static String SAMPLEDOMAIN_NAMSPACE = "http://www.sampledomain.org/sam#";
    public static String SAMPLEDOMAIN_NAMSPACE_PREFIX = "sam";

    public static String ARESOURCE = "AResource";
    public static String PATH_ARESOURCE = "aResource";
    public static String TYPE_ARESOURCE = SAMPLEDOMAIN_NAMSPACE + "AResource";
    
    public static String ANOSLCRESOURCE = "AnOslcResource";
    public static String PATH_ANOSLCRESOURCE = "anOslcResource";
    public static String TYPE_ANOSLCRESOURCE = SAMPLEDOMAIN_NAMSPACE + "AnOslcResource";
    
    public static String ANOTHERRESOURCE = "AnotherResource";
    public static String PATH_ANOTHERRESOURCE = "anotherResource";
    public static String TYPE_ANOTHERRESOURCE = SAMPLEDOMAIN_NAMSPACE + "AnotherResource";

    public static final String HDR_OSLC_VERSION = "OSLC-Core-Version";

}

